<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SeminarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $seminars = [
            [
                'seminar_type' => 'online',
                'name' => 'セミナー01',
                'description' => '説明文01',
                'seminar_date' => '2025-08-25',
                'start_time' => '10:00',
                'end_time' => '11:30',
                'benefits' => '個別相談30分をご利用いただけます',
                'capacity' => 20,
                'company_name' => '税理士事務所サンプル',
                'company_zip' => '224-0053',
                'company_address' => '神奈川県横浜市都筑区池辺町1234',
                'company_building' => 'ABCビル105',
                'company_tel' => '045-513-1732',
                'company_url' => 'https://auntrust.jp',
                'company_email' => 'iguchi@auntrust.jp',
                'company_speaker_info' => '代表：山田太郎',
                'back_url' => 'https://auntrust.jp',
                'finish_url' => 'https://auntrust.jp',
            ],
            [
                'seminar_type' => 'onsite',
                'name' => 'セミナー02',
                'description' => '説明文02',
                'seminar_date' => '2025-08-27',
                'start_time' => '13:00',
                'end_time' => '15:00',
                'benefits' => '資料冊子をプレゼント',
                'capacity' => 30,
                'company_name' => '中小企業診断士事務所',
                'company_zip' => '100-0004',
                'company_address' => '東京都千代田区大手町1-2-3',
                'company_building' => '大手町ビル2F',
                'company_tel' => '03-1234-5678',
                'company_url' => 'https://sample1.jp',
                'company_email' => 'info@sample1.jp',
                'company_speaker_info' => '講師：佐藤一郎',
                'back_url' => 'https://sample1.jp/back',
                'finish_url' => 'https://sample1.jp/finish',
            ],
            [
                'seminar_type' => 'webinar',
                'name' => 'セミナー03',
                'description' => '説明文03',
                'seminar_date' => '2025-08-29',
                'start_time' => '14:00',
                'end_time' => '15:30',
                'benefits' => '録画配信のご案内あり',
                'capacity' => 100,
                'company_name' => '株式会社セミナー企画',
                'company_zip' => '150-0043',
                'company_address' => '東京都渋谷区道玄坂2-8-3',
                'company_building' => '渋谷ビル8F',
                'company_tel' => '03-9876-5432',
                'company_url' => 'https://sample2.jp',
                'company_email' => 'contact@sample2.jp',
                'company_speaker_info' => '登壇者：鈴木花子',
                'back_url' => 'https://sample2.jp/back',
                'finish_url' => 'https://sample2.jp/finish',
            ],
            [
                'seminar_type' => 'online',
                'name' => 'セミナー04',
                'description' => '説明文04',
                'seminar_date' => '2025-09-01',
                'start_time' => '09:30',
                'end_time' => '11:00',
                'benefits' => '参加者限定PDF資料',
                'capacity' => 50,
                'company_name' => '株式会社ITサポート',
                'company_zip' => '530-0011',
                'company_address' => '大阪府大阪市北区大深町4-20',
                'company_building' => 'グランフロント南館9F',
                'company_tel' => '06-1234-4321',
                'company_url' => 'https://sample3.jp',
                'company_email' => 'support@sample3.jp',
                'company_speaker_info' => '講師：高橋健一',
                'back_url' => 'https://sample3.jp/back',
                'finish_url' => 'https://sample3.jp/finish',
            ],
            [
                'seminar_type' => 'onsite',
                'name' => 'セミナー05',
                'description' => '説明文05',
                'seminar_date' => '2025-09-02',
                'start_time' => '15:00',
                'end_time' => '17:00',
                'benefits' => '会場限定ノベルティ',
                'capacity' => 40,
                'company_name' => 'マーケティング研究所',
                'company_zip' => '460-0008',
                'company_address' => '愛知県名古屋市中区栄3-16-1',
                'company_building' => '栄センタービル4F',
                'company_tel' => '052-123-9876',
                'company_url' => 'https://sample4.jp',
                'company_email' => 'info@sample4.jp',
                'company_speaker_info' => '講師：中村明美',
                'back_url' => 'https://sample4.jp/back',
                'finish_url' => 'https://sample4.jp/finish',
            ],
            [
                'seminar_type' => 'webinar',
                'name' => 'セミナー06',
                'description' => '説明文06',
                'seminar_date' => '2025-09-05',
                'start_time' => '18:00',
                'end_time' => '19:30',
                'benefits' => '質問対応あり',
                'capacity' => 80,
                'company_name' => '教育コンサル株式会社',
                'company_zip' => '060-0042',
                'company_address' => '北海道札幌市中央区大通西4-1',
                'company_building' => '札幌プラザ7F',
                'company_tel' => '011-123-0001',
                'company_url' => 'https://sample5.jp',
                'company_email' => 'info@sample5.jp',
                'company_speaker_info' => '講師：小林誠',
                'back_url' => 'https://sample5.jp/back',
                'finish_url' => 'https://sample5.jp/finish',
            ],
            [
                'seminar_type' => 'online',
                'name' => 'セミナー07',
                'description' => '説明文07',
                'seminar_date' => '2025-09-07',
                'start_time' => '11:00',
                'end_time' => '12:30',
                'benefits' => 'ダウンロード資料付き',
                'capacity' => 60,
                'company_name' => 'スタートアップ支援センター',
                'company_zip' => '810-0001',
                'company_address' => '福岡県福岡市中央区天神1-1-1',
                'company_building' => '天神ビル5F',
                'company_tel' => '092-123-5555',
                'company_url' => 'https://sample6.jp',
                'company_email' => 'contact@sample6.jp',
                'company_speaker_info' => '講師：松本大輔',
                'back_url' => 'https://sample6.jp/back',
                'finish_url' => 'https://sample6.jp/finish',
            ],
            [
                'seminar_type' => 'onsite',
                'name' => 'セミナー08',
                'description' => '説明文08',
                'seminar_date' => '2025-09-09',
                'start_time' => '14:00',
                'end_time' => '16:00',
                'benefits' => '無料相談チケット付き',
                'capacity' => 25,
                'company_name' => '不動産コンサルティング株式会社',
                'company_zip' => '980-0021',
                'company_address' => '宮城県仙台市青葉区中央2-3-1',
                'company_building' => '仙台駅前ビル10F',
                'company_tel' => '022-123-1111',
                'company_url' => 'https://sample7.jp',
                'company_email' => 'info@sample7.jp',
                'company_speaker_info' => '講師：田中洋介',
                'back_url' => 'https://sample7.jp/back',
                'finish_url' => 'https://sample7.jp/finish',
            ],
            [
                'seminar_type' => 'webinar',
                'name' => 'セミナー09',
                'description' => '説明文09',
                'seminar_date' => '2025-09-12',
                'start_time' => '13:00',
                'end_time' => '14:30',
                'benefits' => '後日アーカイブ視聴可能',
                'capacity' => 120,
                'company_name' => '人材育成センター',
                'company_zip' => '730-0011',
                'company_address' => '広島県広島市中区基町6-27',
                'company_building' => '広島セミナービル6F',
                'company_tel' => '082-123-2222',
                'company_url' => 'https://sample8.jp',
                'company_email' => 'info@sample8.jp',
                'company_speaker_info' => '講師：加藤優子',
                'back_url' => 'https://sample8.jp/back',
                'finish_url' => 'https://sample8.jp/finish',
            ],
            [
                'seminar_type' => 'online',
                'name' => 'セミナー10',
                'description' => '説明文10',
                'seminar_date' => '2025-09-14',
                'start_time' => '10:00',
                'end_time' => '11:30',
                'benefits' => '電子書籍プレゼント',
                'capacity' => 70,
                'company_name' => '会計士法人サンプル',
                'company_zip' => '980-0811',
                'company_address' => '宮城県仙台市青葉区一番町1-2-3',
                'company_building' => '会計ビル4F',
                'company_tel' => '022-987-6543',
                'company_url' => 'https://sample9.jp',
                'company_email' => 'info@sample9.jp',
                'company_speaker_info' => '講師：伊藤直樹',
                'back_url' => 'https://sample9.jp/back',
                'finish_url' => 'https://sample9.jp/finish',
            ],
            [
                'seminar_type' => 'onsite',
                'name' => 'セミナー11',
                'description' => '説明文11',
                'seminar_date' => '2025-09-16',
                'start_time' => '15:00',
                'end_time' => '17:00',
                'benefits' => '名刺交換会あり',
                'capacity' => 45,
                'company_name' => '士業ネットワーク協会',
                'company_zip' => '540-0031',
                'company_address' => '大阪府大阪市中央区北浜3-2-25',
                'company_building' => '大阪セミナービル2F',
                'company_tel' => '06-5555-7777',
                'company_url' => 'https://sample10.jp',
                'company_email' => 'info@sample10.jp',
                'company_speaker_info' => '講師：山本真理',
                'back_url' => 'https://sample10.jp/back',
                'finish_url' => 'https://sample10.jp/finish',
            ],
            [
                'seminar_type' => 'webinar',
                'name' => 'セミナー12',
                'description' => '説明文12',
                'seminar_date' => '2025-09-18',
                'start_time' => '19:00',
                'end_time' => '20:30',
                'benefits' => '終了後アンケート回答で特典あり',
                'capacity' => 150,
                'company_name' => 'グローバル経営研究所',
                'company_zip' => '810-0041',
                'company_address' => '福岡県福岡市中央区大名1-1-1',
                'company_building' => '大名ビル3F',
                'company_tel' => '092-999-8888',
                'company_url' => 'https://sample11.jp',
                'company_email' => 'info@sample11.jp',
                'company_speaker_info' => '講師：藤田誠一',
                'back_url' => 'https://sample11.jp/back',
                'finish_url' => 'https://sample11.jp/finish',
            ],
        ];
        foreach ($seminars as $seminar) {
            DB::table('seminars')->insert([
                'seminar_type' => $seminar['seminar_type'],
                'name' => $seminar['name'],
                'description' => $seminar['description'],
                'seminar_date' => $seminar['seminar_date'],
                'start_time' => $seminar['start_time'],
                'end_time' => $seminar['end_time'],
                'benefits' => $seminar['benefits'],
                'capacity' => $seminar['capacity'],
                'company_name' => $seminar['company_name'],
                'company_zip' => $seminar['company_zip'],
                'company_address' => $seminar['company_address'],
                'company_building' => $seminar['company_building'],
                'company_tel' => $seminar['company_tel'],
                'company_url' => $seminar['company_url'],
                'company_email' => $seminar['company_email'],
                'company_speaker_info' => $seminar['company_speaker_info'],
                'back_url' => $seminar['back_url'],
                'finish_url' => $seminar['finish_url'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
